[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scustomtkinter"
version = "0.1.1.43"
authors = [
    { name = "aj6cu" }
]
description = "A theme-compliant custom widget library wrapping CustomTkinter."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dependencies = [
    "customtkinter",
    "Pillow",
    "pygubu"
]

[tool.setuptools]
packages = ["scustomtkinter"]
include-package-data = true


[tool.setuptools.package-data]
scustomtkinter = [
    "assets/*.json",
    "assets/images/*.png"
]
